### ISSUE TITLE
Automatic Test Generation

### ISSUE THREAD

**Issue by stevenpeniche** [tdfranklin/newtons-apple#5]
It would be great to have a Rails-like auto test generator feature upon creation of a new component.

**Comment by stevenpeniche** [comment]
@tdfranklin I need to set up a **getTestTemplate** for the test generator. Should we keep all our template fetchers in the template factory or should we separate concerns and create a separate file? This would lead to `component-template-factory`, `test-template-factory`, `redux-template-factory`.

**Comment by tdfranklin** [comment]
@stevenpeniche I'd like to keep the template factory as the actual "fetcher" for all templates (and this might be a good place to turn it into a case statement instead of if/else), but if you need to create a new function or module for some additional logic that's fine.

I just want to keep the template factory as the single "go-between" for the logic and actual templates, so that you send a command to the factory and get back the correct template.  It actually may be a good idea to do some refactoring elsewhere and instead of passing all this logic to the factory, instead simply passing it a string (component, dumb component, test, reducer, etc) and having it be just a big case statement that returns the correct template based on that?  What do you think?

**Comment by stevenpeniche** [comment]
That sounds great! I like the idea of having it be the sole fetcher of templates. I'll proceed with that in mind.

**Comment by stevenpeniche** [comment]
Issue resolved by PR #17
